ccflags-y := -Ofast -ffast-math -fgcse-lm -fgcse-sm -fsched-spec-load -fforce-addr -fsingle-precision-constant -mcpu=cortex-a9 -mtune=cortex-a9 -marm -mfpu=vfpv3-d16 -ftree-vectorize 
obj-y			+= drm/ vga/ stub/ ion/
